package hr.dbab.todokotlin.database

import androidx.room.ColumnInfo
import androidx.room.Entity
import androidx.room.PrimaryKey


@Entity(tableName = "todo_items")
data class ToDoItem(
    @ColumnInfo(name = "item_name")
    val itemName: String,

    @ColumnInfo(name = "item_amount")
    val itemAmount: Int
) {
    // it needs to be of type Long because it is autogenerated
    @PrimaryKey(autoGenerate = true)
    var itemId: Long = 0L
}